dist: bionic
language: ruby 
rvm: 
- 2.3.1
before_install: 
- pip install markdown --user
- wget "https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-1-amd64.deb" "/tmp/pandoc.deb"
- sudo dpkg -i "/tmp/pandoc.deb"
install: 
- bundle install 
deploy: 
    provider: pages
    skip_cleanup: true 
    github_token: $GITHUB_TOKEN 
    local_dir: _site 
    target_branch: master 
    on: 
        branch: source
