title: Warren Alphonso
theme: minima 
description: Built with Jekyll. Hosted on Github Pages. 
markdown: Pandoc

header_pages: 
  - index.md
  - courses.html

collections: 
  projects:
    sequence: true
    output: true
    permalink: /projects/:name
  qc: 
    output: true
    permalink: /qc/:name

google_analytics: UA-147966026-1

defaults: 
  - 
    scope: 
      path: "" # Empty string means all files. 'path' is necessary for defaults. 
      type: "posts" # Possible types are pages, posts, drafts, or any collection. 
    values: 
      layout: "post"
      publish: "true"
      toc: "true"
  - 
    scope: 
      path: ""
      type: "projects"
    values: 
      layout: "page"
  - 
    scope: 
      path: ""
      type: "qc"
    values: 
      layout: "post"
      toc: "true"

toc:
  min_level: 1

pandoc: 
    extensions: 
        - mathjax 
        - from: markdown+fancy_lists+strikeout+tex_math_dollars+pipe_tables+raw_html+markdown_in_html_blocks+fenced_divs+implicit_figures+link_attributes

plugins: 
  - jekyll-toc
  - jekyll-youtube
  - jekyll-last-modified-at
  - jekyll-pandoc


# Exclude these files from the build process results.
# Prevents them from showing up in the master branch which is the live site.
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
