name: Warren Alphonso 
theme: minima 
description: Built with Jekyll. 

header_pages: 
  - index.html
  - qc.html 
  - courses.html

collections: 
  projects:
    sequence: true
    output: true
    permalink: /projects/:name

minima:
  date_format: " "

google_analytics: UA-147966026-1