name: Warren Alphonso 
theme: minima 
description: Built with Jekyll. 

header_pages: 
  - index.html
  - qc.html 
  - courses.html 
  - readings.html

collections: 
  projects:
    sequence: true
    output: true
    permalink: /projects/:name
  writings: 
    output: true 
    permalink: /writings/:name
minima:
  date_format: " "

google_analytics: UA-147966026-1