name: Warren Alphonso 
theme: minima 
description: Built with Jekyll. 

header_pages: 
  - index.md
  - qc.md
  - courses.html
  - readings.md

collections: 
  projects:
    sequence: true
    output: true
    permalink: /projects/:name

google_analytics: UA-147966026-1